Add About me section and contact me section with styling
ybadr99/old_portfolio pull request #2
Opened 2023-01-14 10:26 UTC by ybadr99

add about me section with styling including icons and all styles guideline as Figma
add contact me section with styling

2023-01-14 14:33 UTC, AbayomiOlaoye requested changes
Hi @ybadr99 , 

Good job with this milestone so far!
There are just few more issues to work on before moving onto the next project but you are almost there!

![so_close](https://user-images.githubusercontent.com/99715640/211950260-0e3881c0-9d4f-4ea2-a670-9ef45a23a0f5.gif)

## Highlights
- Descriptive Pull Request message :heavy_check_mark: 
- Good use of GitHub flow :heavy_check_mark: 
- Meaningful commit messages :heavy_check_mark: 
- No linter error :heavy_check_mark: 
- Nice implementation ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 14:33 UTC, AbayomiOlaoye commented on README.md
> -
- [ ] This is a very important part of your ReadMe file as it informs users on how to interact with your contents. Kindly restore it, as it forms part of the requirement.
- [ ] I also noticed that you have removed the file where you have the content. Please do restore that too, and let's make it is correctly linked so that we don't break our code. Broken links are bad for user experience.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +    <main id="myworks">
- Beautiful intuition 😄 👍 
- [ ] Using `main` here may suggest to search engines or users of accessibility devices might deem other parts of the portfolio as unimportant. This section is another standalone part of the document - portfolio, so please kindly change this to `section`.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +        <span>My Recent Works</span>
- [ ] Do you think using an inline tag is really the best? Since there is no special style for any part of `My Recent Works`, I suggest you just use a `hx` tag because that is what it seems like to me. It introduces the entire section - only a `hx` can do this semantically. In this case, I am sure you know that it can't be `h1` because we have used it already, right? 😉

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +
- [ ] As a convention for best practice, leaving extra lines in the code should be avoided as best as one can. Since there is no content here for now, how about removing this line? It makes code more readable.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +        <h1>Profesional Art Printing Data</h1>
- [ ] Like we agreed earlier that we can only have one `h1` in our document according to convention and semantic reasons. Shall we use any other `hx` tag? Yeah, let us 🥺

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +        <h1>Profesional Art Printing Data</h1>
- [ ] Like we agreed earlier that we can only have one `h1` in our document according to convention and semantic reasons. Shall we use any other `hx` tag? Yeah, let us 🥺

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +        <h1>Profesional Art Printing Data</h1>
- [ ] Like we agreed earlier that we can only have one `h1` in our document according to convention and semantic reasons. Shall we use any other `hx` tag? Yeah, let us 🥺

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +        <h1>Profesional Art Printing Data</h1>
- [ ] Like we agreed earlier that we can only have one `h1` in our document according to convention and semantic reasons. Shall we use any other `hx` tag? Yeah, let us 🥺

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +      <h1 id="title">About me</h1>
- [ ] Like we agreed earlier that we can only have one `h1` in our document according to convention and semantic reasons. Shall we use any other `hx` tag? Yeah, let us 🥺

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +        </li>
- [ ] It would be a lot nicer if you can complete your list of skills. I am sure that you can do better than that 😄 . Let's update the list to match up the design correctly.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +          <header><img src="./images/Rectangle 57.png" alt="" /> Skills</header>
- [ ] I don't think that having a `header` tag here is really the best even though it worked. As a professional developer, there are basic conventions and semantics that should pay attention to. You could use a `div` here or just plain `img` tag, or better still for aesthetic touch: you can try using `css pseudo-element`: 
```
selector::before {
  content: url(sample.png);
  position: relative/absolute/fixed; # use one of the three values
  top: 5px;
  left: 5px;
}
```
- [ ] `alt` attribute in `img` tag plays a vital role and I think is better if one includes a descriptive text about the image been uploaded. It is good accessibility reasons and user experience when internet connectivity or server becomes too poor.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +          </header>
- [ ] I don't think that having a `header` tag here is really the best even though it worked. As a professional developer, there are basic conventions and semantics that should pay attention to. You could use a `div` here or just plain `img` tag, or better still for aesthetic touch: you can try using `css pseudo-element`: 
```
selector::before {
  content: url(sample.png);
  position: relative/absolute/fixed; # use one of the three values
  top: 5px;
  left: 5px;
}
```
- [ ] `alt` attribute in `img` tag plays a vital role and I think is better if one includes a descriptive text about the image been uploaded. It is good accessibility reasons and user experience when internet connectivity or server becomes too poor.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +          </header>
- [ ] I don't think that having a `header` tag here is really the best even though it worked. As a professional developer, there are basic conventions and semantics that should pay attention to. You could use a `div` here or just plain `img` tag, or better still for aesthetic touch: you can try using `css pseudo-element`: 
```
selector::before {
  content: url(sample.png);
  position: relative/absolute/fixed; # use one of the three values
  top: 5px;
  left: 5px;
}
```
- [ ] `alt` attribute in `img` tag plays a vital role and I think is better if one includes a descriptive text about the image been uploaded. It is good accessibility reasons and user experience when internet connectivity or server becomes too poor.

2023-01-14 14:33 UTC, AbayomiOlaoye commented on index.html
> +      <button id="download">Get My Resume</button>
- [ ] Kindly check the value of the fonts that I annotated in the figure below and let us match them with figma design:

|Your Design| Figma Design|
|:--------------:|:-----------------:|
|![image](https://user-images.githubusercontent.com/99715640/212476516-e0b28008-cddf-4320-8728-8210a345d7ec.png)|![image](https://user-images.githubusercontent.com/99715640/212476543-4f2f3f7b-26de-449b-a09f-de5ee4611ca6.png)|

- For `#title`, the `font-size` is smaller than it is on figma while that of the paragraph is too larger. This anomaly is having great impact on your design at the moment. Please check it
- [ ] For `button`, we are asked to style our buttons to make it interactive even though we are not using JavaScript and this is good for user experience. Interactivity like `hover`, `enabled`, `disabled` and `active`.  You will find 👇 on figma: 

![image](https://user-images.githubusercontent.com/99715640/212477004-fe39ea13-227e-479f-a098-73de3021fc12.png)

- [ ] Please try to make all your buttons have all the interactive states mentioned above with the specified properties.

2023-01-14 14:55 UTC, ybadr99 commented on README.md
> -
I removed it because I revied feedback to remove it

2023-01-14 14:58 UTC, ybadr99 commented on index.html
> +    <main id="myworks">
my problem was h1 show so bold

2023-01-14 16:56 UTC, Owusu-Desmond approved these changes
Hi @ybadr99 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Great working on the setup of the project ✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-16 10:58 UTC, merged

2023-01-24 07:37 UTC, Atril33 commented
Hi! [ybadr99](https://github.com/ybadr99)
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉
![congratulation](https://user-images.githubusercontent.com/118503473/214235954-191f51fb-d62f-4447-a576-d19c62ce9cf1.gif)
# Highlights

1. No Linters error ✅
2.  Descriptive pull request✅
3. Good commit messages ✅
4. Professional README file ✅

2023-01-24 07:55 UTC, LoviMadaan commented
### Hi @ybadr99, 👋,
Status: **Approved** 🟢
Your project is complete! There is nothing else to say other than... it's time to  
Congratulations! 🎉

![image](https://user-images.githubusercontent.com/119787828/214238837-60f31139-7f3d-4b24-a0a9-a05c6fefc488.png)

**Highlights**
Good use of Github's Review Changes Feature ✔️
Good use of inline comments ✔️
Suggestions were polite ✔️
Reasons for recommended changes were given ✔️
Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.