Add contact-me form with styling
ybadr99/old_portfolio pull request #4
Opened 2023-01-17 17:27 UTC by ybadr99

add contact-me form with styling & make form validation & use formspree to get  forms values

2023-01-17 18:06 UTC, Gambit142 requested changes
Hi @ybadr99 👋, 

Good job so far!

## Highlights
- All linters checks passed ✔️ 
- README.md is professional ✔️ 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-01-17 18:06 UTC, Gambit142 commented on index.html
> +          ></textarea>
- [ ] Kindly reduce the number of rows to `3` or `4` so that it can look like the Figma template that you chose.

### Your Design

![image](https://user-images.githubusercontent.com/77106962/212975880-8deaccb5-5222-47fc-83e2-1df3adc880ce.png)

### Figma Design

![image](https://user-images.githubusercontent.com/77106962/212975959-bca27c46-2e1d-4162-a487-1de12148f2b5.png)

2023-01-17 18:06 UTC, Gambit142 commented on style.css
> +}
- [ ] Kindly use the `Inter` font-family for this input. One of the requirements is to use the fonts used in the Figma template. Kindly implement this. 👍

2023-01-17 18:06 UTC, Gambit142 commented on style.css
> +}
Kindly use the Inter font-family for this input. One of the requirements is to use the fonts used in the Figma template. Kindly implement this. 👍

2023-01-18 16:46 UTC, Tadesse-Alemayehu requested changes
### Hi @ybadr99 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)

## Highlights
 - [ ] Good job making most of the changes requested by the previous code reviewer. ✅
 - [ ] Good job overall following the template design ✅
 - [ ]  Correct GitHub Flow  ✅
 - [ ]  Good commit history  ✅
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-18 16:46 UTC, Tadesse-Alemayehu commented on style.css
> +}
- [ ] Dear @ybadr99, Good job adding the inter font for the `h3` and `button` elements following the requested changes. But as the previous code reviewer mentioned we need to set the font for the `textarea` to `Inter`. Please update your font family accordingly.

![Screenshot 2023-01-18 193940](https://user-images.githubusercontent.com/69077061/213241773-4c3f508d-71f9-47d9-8b86-73e74875d6e5.png)

2023-01-18 16:46 UTC, TadesseDev commented on style.css
> +}
- [ ] Dear @ybadr99, Good job adding the inter font for the `h3` and `button` elements following the requested changes. But as the previous code reviewer mentioned we need to set the font for the `input fields` to `Inter`. Please update your font family accordingly.

2023-01-19 00:46 UTC, Shedrack-Sunday approved these changes
Hi @ybadr99 👋 
 
 # STATUS: APPROVED ✔️  🍾  🥳

 Your project is complete! There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉

 ![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)
 
 ## Highlights
- Proper use of Github features 💯 
- Good commit messages 
 
 ## Optional suggestions
 _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
 
 - [  ] I made very important suggestions on the footer setting of your page, and I strongly advice you to check the comments to fix it. 👍 
 

 Cheers and Happy coding!👏👏👏
 
 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-19 00:46 UTC, Shedrack-Sunday commented on style.css
> +}
-[Optional] I strongly suggset you fix the outline of the cocials, as they currently look out of place and far from the one given on the figma design. An appealing UI is the first catch of interest of a potential user, and you would want to make it as good as possible 

# Your design:
![image](https://user-images.githubusercontent.com/50990925/213328993-54285854-4e86-4452-881e-c96eb5cb3e0a.png)

# Figma:
![image](https://user-images.githubusercontent.com/50990925/213329111-4f667567-93f1-456f-b0a7-cf5b2ea64e9e.png)

2023-01-19 00:50 UTC, merged

2023-01-24 13:16 UTC, Favourezeugwa reviewed
## STATUS: APPROVED 🥇 🏆 🍹 

Hi @ybadr99 ,

I am Favour 👩🏽 , your reviewer for this PR.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Yayyy! 💃🏽, Congratulations! 🎉 🎉🎉

![happy](https://user-images.githubusercontent.com/99246359/202491301-53f8c6a2-8ff4-4337-9b6b-9c75c8bdf345.gif)

## Highlights 💯 
- No Linter errors ✔️
- Good commit messages ✔️
- Professional Readme file ✔️
- Descriptive PR ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._