navbar menu on mobile version
ybadr99/old_portfolio pull request #8
Opened 2023-02-07 20:15 UTC by ybadr99

- Add navbar menu 
- using JS to show navbar menu on click

2023-02-07 20:57 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/33840476/192236577-e2d71173-44d8-4ac8-9615-bf78ba730792.gif)


## Required Changes ♻️

- [ ] The MIT license of your repo is not properly set. Kindly follow this [link](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) to properly set it up.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 20:57 UTC, Qoosim commented on src/script.js
> +});
- [ ] Wonderful job so far, however, the behaviour of your mobile menu is not consistent. At first page load, everything seems fine, the hamburger brings out the mobile menu when it is clicked. But sometimes, the page does not scroll to the appropriate section of the page when any of the menu items is clicked.  Please, take a look. :point_down: 

[mobile-menu-behaviour.webm](https://user-images.githubusercontent.com/26597432/217362603-2929d05d-05e4-45b1-9bd4-7cd4d093b8e6.webm)

[mobile-menu-2.webm](https://user-images.githubusercontent.com/26597432/217362652-f4adf4d4-cc4b-4303-813b-5c7267c7176e.webm)

2023-02-07 21:18 UTC, ybadr99 commented on src/script.js
> +});
hey 
thanks for the good review 
now, I know the issue and gonna to fix it

2023-02-07 21:21 UTC, ybadr99 commented on src/script.js
> +});
I had pushed MIT license on the main branch

2023-02-07 21:43 UTC, brainconnect93 requested changes
### Hi @ybadr99, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.tenor.com/isiLRnxz3zwAAAAM/cat-driving-serious.gif" width="500px" height="300px">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [ ] Great effort working on the changes requested by the previous reviewer, but currently the MIT license link is still not fixed yet as the link is still broken. Kindly fix it
> N.B: If you need help to get this fix kindly reach out and i would be glad to render an helping hand.
MIT image 👇 

![mit](https://user-images.githubusercontent.com/78634841/217373258-3e38761a-c499-44c2-912a-889ca9407676.png)


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-07 22:49 UTC, ybadr99 commented
I'm already fixed it in the main branch 
![Screenshot from 2023-02-08 00-48-55](https://user-images.githubusercontent.com/61107698/217384715-db161752-bfee-4c00-999f-66dea2f09292.png)

2023-02-08 00:35 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @ybadr99, 👋 

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

<img src="https://media.tenor.com/ipGxBQElNzYAAAAM/approved-ymaz.gif" width="500px">

## Good Points 👍

- Has a proper Pull Request. ✔️
- No Linter errors ✔️
- Good use of Github flow ✔️

### Changes Required ♻️

- [x]  _Please check the comments under the review._

### Optional Changes 🔥

Thank You.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-08 01:17 UTC, merged